### ISSUE TITLE
Preferences Crash

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#323] opened 2022-03-12 19:26 UTC
Going to "File"->"Settings"->"Circuit" and clicking the Arrow left to "Circuit" makes Antares infinitely crash. Only solvable with Taskmanager Shutdown.

**Comment by flandreas** [comment] 2022-03-13 10:16
@leonuetzel Thank you for reporting this. I can't reproduce the problem on any of my machines (Mac, Windows).

Could you please produce it once more, then kill Antares, and then grab your log file and attach it to this issue? If you are on Windows, you find the log file in ..\Users\YOUR_USER_NAME\AppData\Roaming\Antares\Antares.log

**Comment by leonuetzel** [comment] 2022-03-13 10:19
[Antares.log](https://github.com/flandreas/antares/files/8239330/Antares.log)

**Comment by flandreas** [comment] 2022-03-13 10:38
@leonuetzel Thanks for your quick response!

There is a text missing in the German translation files. I couldn't reproduce it because I've tested with English.

If you want to explore the new preference, you could workaround the problem by temporarily changing your language to English, explore/change the new preference, and then switch back to German.

**Comment by flandreas** [comment] 2022-03-13 10:40
Developer note: Missing german translation for antares.preferences.group.expression.

**Comment by leonuetzel** [comment] 2022-03-13 10:43
Ok, thank you.

**Comment by flandreas** [comment] 2022-03-16 16:14
Released with 0.22.0

**Closed by flandreas** 2022-03-16 16:14 UTC
Labels: bug, done
