### ISSUE TITLE
Register n Bit not working

### ISSUE THREAD

**Issue by XBlayz** [flandreas/antares#608] opened 2023-08-06 17:19 UTC
The component "Register n Bit" doesn't work, the output is always floating.

<img width="594" alt="Screenshot 2023-08-06 191749" src="https://github.com/flandreas/antares/assets/73166431/c189a853-7cf1-484b-a57a-563137701319">

Version 1.5.0, Windows 11.

**Comment by flandreas** [comment] 2023-08-08 17:43
@XBlayz Thank you for reporting this.

The cause of the bug is that in the library component "Register n Bit", property "Always use function" is not set. It should be set, because it is a purely scripted component (no inner circuit).

Therefore, the component does nothing if the simulation is run with mode "View -> Deep Simulation". As a workaround, run your circuit without mode "View -> Deep Simulation" enabled, i.e. in mode "Shallow Simulation".

Will be fixed with the next release, upcoming soon.

**Comment by XBlayz** [comment] 2023-08-08 17:47
Ok, thanks for the help.

**Closed** 2023-08-20 11:27 UTC
Labels: bug, done
