### ISSUE TITLE
'Internally' Name in Button not always working when Symbol is placed 

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#160] opened 2021-06-08 15:24 UTC
I have a Symbol with just two Buttons and two outputs but no background. Sometimes, when placing the component or re-opening a circuit where the button is used, the 'Internally' Name for one of the buttons is missing. 
In situ within the circuit: 
![image](https://user-images.githubusercontent.com/25486087/121212283-7c7d8480-c87d-11eb-8591-5d200b4148e3.png)
In the Explorer Preview: 
![image](https://user-images.githubusercontent.com/25486087/121212359-8f905480-c87d-11eb-8ef1-a5a2359b60ce.png)
In the Component Circuit: 
![image](https://user-images.githubusercontent.com/25486087/121212466-ac2c8c80-c87d-11eb-9b3f-bf72b4327c2d.png)
In the Component Symbol: 
![image](https://user-images.githubusercontent.com/25486087/121212534-bd759900-c87d-11eb-852a-1023a547f57a.png)

After changing the 'Label Position' Property for the switch to 'Externally' and back to 'Internally' and saving will fix the problem: 
![image](https://user-images.githubusercontent.com/25486087/121213003-278e3e00-c87e-11eb-999e-bd7820eaf29c.png)

But when moving the Component into a User Folder the problem reappears and the aforementioned steps need to be performed again.

**Comment by flandreas** [comment] 2021-06-09 05:39
Okay, thank you for reporting this.

**Comment by flandreas** [comment] 2021-06-09 17:16
Couldn't reproduce the problem, but found and fixed a bug in the "controls" code where IDs of control's view and model where confused when updating controls in symbols. This could explain the problem here, but I'm not entirely sure.

I'm closing this issue; please feel free to reopen it if the problem persists after installing the new release

**Comment by richardabendroth** [comment] 2021-06-09 20:39
It's really hard to reproduce. Sometimes it happens when I change something in the circuit, sometimes not. Sometimes when Moving the Circuit into a User Folder, sometimes not. But what you are saying sounds like it could cause the problem.

**Closed** 2021-06-10 08:24 UTC
Labels: bug, done
