### ISSUE TITLE
Simulation stopped working altogether

### ISSUE THREAD

**Issue by Kitick** [flandreas/antares#82] opened 2021-05-13 23:00 UTC
Back to working on a little mini 8 bit computer project, I set up a small setup with a keyboard input and RAM, just to test the bus transfers, and a basic control logic, and the simulation is just refusing to play anymore. Correction actually, it plays for a little bit, then gets to a point and then freezes.

I have no idea if its a wired connection I did, or if its something else. No simulation speed setting changes this. The clock doesn't obsolete, and switches don't push values.

Here's a image of my setup; forgive any wired wirings, its just for testing proposes for now.

![image](https://user-images.githubusercontent.com/34259991/118197610-26472e00-b404-11eb-9bac-32d7f9db88f9.png)
![image](https://user-images.githubusercontent.com/34259991/118197666-3eb74880-b404-11eb-8c50-67070172c218.png)

**Comment by flandreas** [comment] 2021-05-14 04:55
Could you please start Antares once more and run the simulation until the problem occurs, and then export the log file using menu "File -> Export Log" and attach the exported log file to this issue? And if you don't mind, may I ask to you to also export your project using "File -> Projects -> Export" and attach it as well so I can analyze what's going on in your circuit?

**Comment by Kitick** [comment] 2021-05-14 05:24
Alright, at least what I can read from this its a null pointer, so I added something incorrectly?

Also I'm not able to open projects, its greyed out, even though I have a project just to store everything. That does remind me, I should make my computer its own project, rather than a circuit. But for now ill leave it as is.

Heres the log file though: [Antares.log](https://github.com/flandreas/antares/files/6476665/Antares.log)

![Screenshot (2)](https://user-images.githubusercontent.com/34259991/118225395-e56a0c00-b439-11eb-8225-04ad413c4e13.png)

**Comment by flandreas** [comment] 2021-05-14 05:46
Thank you for the log file.

No, you didn't do anything incorrectly, this is surely a bug in Antares.

The "Projects.." menu item is disabled because the simulation is still running. Please stop the simulation (or restart Antares, if the "Start/Stop" button isn't responsive any more), and try again to export the project. It would tremendously help me to find the cause of the problem.

**Comment by Kitick** [comment] 2021-05-14 05:50
Ah silly me, didn't even think to try that!

Anyway, here it is: [Personal.zip](https://github.com/flandreas/antares/files/6476793/Personal.zip)

**Comment by flandreas** [comment] 2021-05-14 06:51
Thank you very much for providing the project.

I figured out that the source of the problem is Antares' implementation of the RAM component. It throws an exception if input A is "undefined (blue)" while CLK is asserted. This is cleary a bug and will be fixed with the next release. The proper behavior would probably be to make output D also undefined in this case. Thank you again for reporting this.

In the meantime, you could temporarily change your circuit so that CS of the RAM is only asserted if A is defined.

**Closed** 2021-05-16 16:48 UTC
Labels: bug, done
