### ISSUE TITLE
Simulation and Editing large Circuits takes very long

### ISSUE THREAD

**Issue by leonuetzel** [flandreas/antares#301] opened 2022-02-06 16:58 UTC
I tried to simulate a quite big circuit and started the Simulation (Flat Simulation without showing Simulation Time) and waited for the Simulation to start. After 2 Hours it wasnt ready so i cancelled. CPU: i7-5500U, so not the slowest CPU...
Is it possible to optimize the Program so it simulates faster or maybe uses more Processor-Cores?

Similar Problem when drawing large Circuits: the Program freezes from time to time for like 5-10 secs if u edit something (maybe java garbagecollector?)

**Comment by flandreas** [comment] 2022-02-06 19:17
@leonuetzel Thank you for reporting this. Would you mind exporting and attaching your project so I can do some analysis?

**Comment by leonuetzel** [comment] 2022-02-06 19:19
[CPU.zip](https://github.com/flandreas/antares/files/8011044/CPU.zip)

**Comment by flandreas** [comment] 2022-02-06 19:41
Thank you. This is truly the largest Antares project I have ever seen. I'll use it to try to optimize various parts of Antares. Thanks again for sharing.

**Comment by leonuetzel** [comment] 2022-02-06 19:43
Yeah no problem. Try to edit some Things and you will see, that it freezes sometimes. I also noticed, that once a Simulation was loaded, restarting it was quite fast.

**Comment by flandreas** [comment] 2022-02-07 11:08
Performance at simulation start extracted to separate issue #302. With the current fix, I'm able to start the simulation of your CPU in about 10 secs on my machine.

**Comment by flandreas** [comment] 2022-02-07 19:21
@leonuetzel Simulation startup performance fixed with release 0.19.0. I couldn't reproduce the performance lags when editing your project, but your assumption (Java GC) could be right. I will keep track of this issue.

**Closed** 2022-02-09 13:08 UTC
Labels: analysis
